Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      sudo mkdir /root/.ssh/
      sudo echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      sudo echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
      sudo echo "# test" >> /etc/ssh/sshd_config
      sudo /etc/init.d/ssh restart
      sudo apt-get install -y python
    SHELL
  end
  config.vm.provider  "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
